#Service ID
dismiss_alert:
  name: Dismiss alert
  description: Dismiss an alert
  target:
    entity:
      integration: linktap
      domain: binary_sensor

dismiss_alerts:
  name: Dismiss alerts
  description: Dismiss all alerts
  target:
    entity:
      integration: linktap
      domain: binary_sensor

pause:
  name: Pause
  description: Pause watering for the specified duration
  fields:
    hours:
      name: Hours
      example: 1
      description: Duration in hours
  target:
    entity:
      integration: linktap
      domain: switch

pause_valve:
  name: Pause
  description: Pause watering for the specified duration
  fields:
    hours:
      name: Hours
      example: 1
      description: Duration in hours
  target:
    entity:
      integration: linktap
      domain: valve

start_watering:
  name: Start watering
  description: Start watering for the specified duration
  fields:
    seconds:
      name: Duration
      example: 900
      description: Watering duration in seconds
  target:
    entity:
      integration: linktap
      domain: valve
